In [4]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("product_info.csv")
df.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [9]:
df.shape

(8494, 27)

In [10]:
df.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   object
 1   product_name        8494 non-null   object
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   object
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   object
 8   variation_type      7050 non-null   object
 9   variation_value     6896 non-null   object
 10  variation_desc      1250 non-null   object
 11  ingredients         7549 non-null   object
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   object
 21  primary_category    8494 non-null   object
 22  secondary_category  8486 non-null   object
 23  tertiary_category   7504 non-null   object
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), object(12)
memory usage: 1.7+ MB

In [12]:
df.isnull().sum()

product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                278
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd       8043
sale_price_usd        8224
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
child_count              0
child_max_price       5740
child_min_price       5740
dtype: int64

In [13]:
df["ingredients"].head()

0    ['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...
1    ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
2    ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
3    ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
4    ['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...
Name: ingredients, dtype: object

In [14]:
df["rating"].describe()

count    8216.000000
mean        4.194513
std         0.516694
min         1.000000
25%         3.981725
50%         4.289350
75%         4.530525
max         5.000000
Name: rating, dtype: float64

In [16]:
df["primary_category"].value_counts()

primary_category
Skincare           2420
Makeup             2369
Hair               1464
Fragrance          1432
Bath & Body         405
Mini Size           288
Men                  60
Tools & Brushes      52
Gifts                 4
Name: count, dtype: int64

In [17]:
skincare_df = df[df["primary_category"] == "Skincare"]

In [18]:
skincare_df.shape

(2420, 27)

In [19]:
important_columns = [
    "product_name",
    "brand_name",
    "ingredients",
    "rating",
    "reviews",
    "price_usd",
    "highlights",
    "primary_category",
    "secondary_category"
]

skincare_df = skincare_df[important_columns]

In [20]:
skincare_df.isnull().sum()

product_name            0
brand_name              0
ingredients           134
rating                 69
reviews                69
price_usd               0
highlights            417
primary_category        0
secondary_category      0
dtype: int64

In [21]:
skincare_df = skincare_df.dropna(subset=["ingredients"])

In [22]:
skincare_df.shape

(2286, 9)

In [23]:
skincare_df["rating"] = skincare_df["rating"].fillna(skincare_df["rating"].mean())

In [24]:
skincare_df.head()

,product_name,brand_name,ingredients,rating,reviews,price_usd,highlights,primary_category,secondary_category
89,GENIUS Sleeping Collagen Moisturizer,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",4.5413,1321.0,98.0,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Moisturizers
90,GENIUS Liquid Collagen Serum,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",4.0259,1159.0,115.0,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Treatments
91,Triple Algae Eye Renewal Balm Eye Cream,Algenist,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",4.5306,1142.0,68.0,NaN,Skincare,Eye Care
92,GENIUS Liquid Collagen Lip Treatment,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",3.8721,649.0,29.0,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Skincare,Lip Balms & Treatments
93,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,Algenist,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",4.4134,508.0,28.0,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Skincare,Sunscreen

In [25]:
skincare_df.to_csv("cleaned_skincare.csv", index=False)